/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Team, Sticker, TradeOffer, CollectionState } from './types';

export const TEAMS: Team[] = [
  // Group A
  { name: "Mexico", code: "MEX", group: "Group A", flagEmoji: "🇲🇽", fedName: "Federación Mexicana de Fútbol" },
  { name: "Czechia", code: "CZE", group: "Group A", flagEmoji: "🇨🇿", fedName: "Fotbalová asociace České republiky" },
  { name: "Korea Republic", code: "KOR", group: "Group A", flagEmoji: "🇰🇷", fedName: "Korea Football Association" },
  { name: "South Africa", code: "RSA", group: "Group A", flagEmoji: "🇿🇦", fedName: "South African Football Association" },

  // Group B
  { name: "Canada", code: "CAN", group: "Group B", flagEmoji: "🇨🇦", fedName: "Canada Soccer Association" },
  { name: "Qatar", code: "QAT", group: "Group B", flagEmoji: "🇶🇦", fedName: "Qatar Football Association" },
  { name: "Switzerland", code: "SUI", group: "Group B", flagEmoji: "🇨🇭", fedName: "Association Suisse de Football" },
  { name: "Bosnia & Herzegovina", code: "BIH", group: "Group B", flagEmoji: "🇧🇦", fedName: "Nogometni Savez Bosne i Hercegovine" },

  // Group C
  { name: "Brazil", code: "BRA", group: "Group C", flagEmoji: "🇧🇷", fedName: "Confederação Brasileira de Futebol" },
  { name: "Morocco", code: "MAR", group: "Group C", flagEmoji: "🇲🇦", fedName: "Fédération Royale Marocaine de Football" },
  { name: "Haiti", code: "HAI", group: "Group C", flagEmoji: "🇭🇹", fedName: "Fédération Haïtienne de Football" },
  { name: "Scotland", code: "SCO", group: "Group C", flagEmoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", fedName: "Scottish Football Association" },

  // Group D
  { name: "United States", code: "USA", group: "Group D", flagEmoji: "🇺🇸", fedName: "United States Soccer Federation" },
  { name: "Paraguay", code: "PAR", group: "Group D", flagEmoji: "🇵🇾", fedName: "Asociación Paraguaya de Fútbol" },
  { name: "Australia", code: "AUS", group: "Group D", flagEmoji: "🇦🇺", fedName: "Football Australia" },
  { name: "Türkiye", code: "TUR", group: "Group D", flagEmoji: "🇹🇷", fedName: "Türkiye Futbol Federasyonu" },

  // Group E
  { name: "Germany", code: "GER", group: "Group E", flagEmoji: "🇩🇪", fedName: "Deutscher Fußball-Bund" },
  { name: "Curaçao", code: "CUW", group: "Group E", flagEmoji: "🇨🇼", fedName: "Federashon Futbol Korsou" },
  { name: "Ivory Coast", code: "CIV", group: "Group E", flagEmoji: "🇨🇮", fedName: "Fédération Ivoirienne de Football" },
  { name: "Ecuador", code: "ECU", group: "Group E", flagEmoji: "🇪🇨", fedName: "Federación Ecuatoriana de Fútbol" },

  // Group F
  { name: "Netherlands", code: "NED", group: "Group F", flagEmoji: "🇳🇱", fedName: "Koninklijke Nederlandse Voetbalbond" },
  { name: "Japan", code: "JPN", group: "Group F", flagEmoji: "🇯🇵", fedName: "Japan Football Association" },
  { name: "Tunisia", code: "TUN", group: "Group F", flagEmoji: "🇹🇳", fedName: "Fédération Tunisienne de Football" },
  { name: "Sweden", code: "SWE", group: "Group F", flagEmoji: "🇸🇪", fedName: "Svenska Fotbollförbundet" },

  // Group G
  { name: "Belgium", code: "BEL", group: "Group G", flagEmoji: "🇧🇪", fedName: "Royal Belgian Football Association" },
  { name: "Egypt", code: "EGY", group: "Group G", flagEmoji: "🇪🇬", fedName: "Egyptian Football Association" },
  { name: "Iran", code: "IRN", group: "Group G", flagEmoji: "🇮🇷", fedName: "Football Federation Islamic Republic of Iran" },
  { name: "New Zealand", code: "NZL", group: "Group G", flagEmoji: "🇳🇿", fedName: "New Zealand Football" },

  // Group H
  { name: "Spain", code: "ESP", group: "Group H", flagEmoji: "🇪🇸", fedName: "Real Federación Española de Fútbol" },
  { name: "Saudi Arabia", code: "KSA", group: "Group H", flagEmoji: "🇸🇦", fedName: "Saudi Arabian Football Federation" },
  { name: "Cape Verde", code: "CPV", group: "Group H", flagEmoji: "🇨🇻", fedName: "Federação Caboverdiana de Futebol" },
  { name: "Uruguay", code: "URU", group: "Group H", flagEmoji: "🇺🇾", fedName: "Asociación Uruguaya de Fútbol" },

  // Group I
  { name: "France", code: "FRA", group: "Group I", flagEmoji: "🇫🇷", fedName: "Fédération Française de Football" },
  { name: "Senegal", code: "SEN", group: "Group I", flagEmoji: "🇸🇳", fedName: "Fédération Sénégalaise de Football" },
  { name: "Iraq", code: "IRQ", group: "Group I", flagEmoji: "🇮🇶", fedName: "Iraq Football Association" },
  { name: "Norway", code: "NOR", group: "Group I", flagEmoji: "🇳🇴", fedName: "Norges Fotballforbund" },

  // Group J
  { name: "Argentina", code: "ARG", group: "Group J", flagEmoji: "🇦🇷", fedName: "Asociación del Fútbol Argentino" },
  { name: "Algeria", code: "ALG", group: "Group J", flagEmoji: "🇩🇿", fedName: "Fédération Algérienne de Football" },
  { name: "Austria", code: "AUT", group: "Group J", flagEmoji: "🇦🇹", fedName: "Österreichischer Fußball-Bund" },
  { name: "Jordan", code: "JOR", group: "Group J", flagEmoji: "🇯🇴", fedName: "Jordan Football Association" },

  // Group K
  { name: "Portugal", code: "POR", group: "Group K", flagEmoji: "🇵🇹", fedName: "Federação Portuguesa de Futebol" },
  { name: "Colombia", code: "COL", group: "Group K", flagEmoji: "🇨🇴", fedName: "Federación Colombiana de Fútbol" },
  { name: "Uzbekistan", code: "UZB", group: "Group K", flagEmoji: "🇺🇿", fedName: "Uzbekistan Football Association" },
  { name: "DR Congo", code: "COD", group: "Group K", flagEmoji: "🇨🇩", fedName: "Fédération Congolaise de Football-Association" },

  // Group L
  { name: "England", code: "ENG", group: "Group L", flagEmoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", fedName: "The Football Association" },
  { name: "Croatia", code: "CRO", group: "Group L", flagEmoji: "🇭🇷", fedName: "Hrvatski nogometni savez" },
  { name: "Ghana", code: "GHA", group: "Group L", flagEmoji: "🇬🇭", fedName: "Ghana Football Association" },
  { name: "Panama", code: "PAN", group: "Group L", flagEmoji: "🇵🇦", fedName: "Federación Panameña de Fútbol" }
];

// Actual sticker dataset from the Panini FIFA World Cup 2026 checklist.
// Team sticker names intentionally omit the trailing nation in brackets.
const PLAYER_NAMES_BY_TEAM: { [code: string]: { [n: number]: string } } = {
  "ALG": {
    "1": "Emblem",
    "2": "Alexis Guendouz",
    "3": "Ramy Bensebaini",
    "4": "Youcef Atal",
    "5": "Rayan Aït-Nouri",
    "6": "Mohamed Amine Tougai",
    "7": "Aïssa Mandi",
    "8": "Ismael Bennacer",
    "9": "Houssem Aouar",
    "10": "Hicham Boudaoui",
    "11": "Ramiz Zerrouki",
    "12": "Nabil Bentaleb",
    "13": "Team Photo",
    "14": "Farés Chaibi",
    "15": "Riyad Mahrez",
    "16": "Saïd Benrahma",
    "17": "Anis Hadj Moussa",
    "18": "Amine Gouiri",
    "19": "Baghdad Bounedjah",
    "20": "Mohammed Amoura"
  },
  "ARG": {
    "1": "Emblem",
    "2": "Emiliano Martínez",
    "3": "Nahuel Molina",
    "4": "Cristian Romero",
    "5": "Nicolás Otamendi",
    "6": "Nicolás Tagliafico",
    "7": "Leonardo Balerdi",
    "8": "Enzo Fernández",
    "9": "Alexis Mac Allister",
    "10": "Rodrigo De Paul",
    "11": "Exequiel Palacios",
    "12": "Leandro Paredes",
    "13": "Team Photo",
    "14": "Nico Paz",
    "15": "Franco Mastantuono",
    "16": "Nico González",
    "17": "Lionel Messi",
    "18": "Lautaro Martínez",
    "19": "Julián Álvarez",
    "20": "Giuliano Simeone"
  },
  "AUS": {
    "1": "Emblem",
    "2": "Mathew Ryan",
    "3": "Joe Gauci",
    "4": "Harry Souttar",
    "5": "Alessandro Circati",
    "6": "Jordan Bos",
    "7": "Aziz Behich",
    "8": "Cameron Burgess",
    "9": "Lewis Miller",
    "10": "Milos Degenek",
    "11": "Jackson Irvine",
    "12": "Riley McGree",
    "13": "Team Photo",
    "14": "Aiden O'Neill",
    "15": "Connor Metcalfe",
    "16": "Patrick Yazbek",
    "17": "Craig Goodwin",
    "18": "Kusini Yengi",
    "19": "Nestory Irankunda",
    "20": "Mohamed Touré"
  },
  "AUT": {
    "1": "Emblem",
    "2": "Alexander Schlager",
    "3": "Patrick Pentz",
    "4": "David Alaba",
    "5": "Kevin Danso",
    "6": "Philipp Lienhart",
    "7": "Stefan Posch",
    "8": "Philipp Mwene",
    "9": "Alexander Prass",
    "10": "Xaver Schlager",
    "11": "Marcel Sabitzer",
    "12": "Konrad Laimer",
    "13": "Team Photo",
    "14": "Florian Grillitsch",
    "15": "Nicolas Seiwald",
    "16": "Romano Schmid",
    "17": "Patrick Wimmer",
    "18": "Christoph Baumgartner",
    "19": "Michael Gregoritsch",
    "20": "Marko Arnautović"
  },
  "BEL": {
    "1": "Emblem",
    "2": "Thibaut Courtois",
    "3": "Arthur Theate",
    "4": "Timothy Castagne",
    "5": "Zeno Debast",
    "6": "Brandon Mechele",
    "7": "Maxim De Cuyper",
    "8": "Thomas Meunier",
    "9": "Youri Tielemans",
    "10": "Amadou Onana",
    "11": "Nicolas Raskin",
    "12": "Alexis Saelemaekers",
    "13": "Team Photo",
    "14": "Hans Vanaken",
    "15": "Kevin De Bruyne",
    "16": "Jérémy Doku",
    "17": "Charles De Ketelaere",
    "18": "Leandro Trossard",
    "19": "Loïs Openda",
    "20": "Romelu Lukaku"
  },
  "BIH": {
    "1": "Emblem",
    "2": "Nikola Vasilj",
    "3": "Amer Dedić",
    "4": "Sead Kolašinac",
    "5": "Tarik Muharemović",
    "6": "Nihad Mujakić",
    "7": "Nikola Katić",
    "8": "Amir Hadžiahmetović",
    "9": "Benjamin Tahirović",
    "10": "Armin Gigović",
    "11": "Ivan Šunjić",
    "12": "Ivan Bašić",
    "13": "Team Photo",
    "14": "Dženis Burnić",
    "15": "Esmir Bajraktarević",
    "16": "Amar Memić",
    "17": "Ermedin Demirović",
    "18": "Edin Džeko",
    "19": "Samed Baždar",
    "20": "Haris Tabaković"
  },
  "BRA": {
    "1": "Emblem",
    "2": "Alisson",
    "3": "Bento",
    "4": "Marquinhos",
    "5": "Éder Militão",
    "6": "Gabriel Magalhães",
    "7": "Danilo",
    "8": "Wesley",
    "9": "Lucas Paquetá",
    "10": "Casemiro",
    "11": "Bruno Guimarães",
    "12": "Luiz Henrique",
    "13": "Team Photo",
    "14": "Vinícius Júnior",
    "15": "Rodrygo",
    "16": "João Pedro",
    "17": "Matheus Cunha",
    "18": "Gabriel Martinelli",
    "19": "Raphinha",
    "20": "Estêvão"
  },
  "CAN": {
    "1": "Emblem",
    "2": "Dayne St. Clair",
    "3": "Alphonso Davies",
    "4": "Alistair Johnston",
    "5": "Samuel Adekugbe",
    "6": "Richie Laryea",
    "7": "Derek Cornelius",
    "8": "Moïse Bombito",
    "9": "Kamal Miller",
    "10": "Stephen Eustáquio",
    "11": "Ismaël Koné",
    "12": "Jonathan Osorio",
    "13": "Team Photo",
    "14": "Jacob Shaffelburg",
    "15": "Mathieu Choinière",
    "16": "Niko Sigur",
    "17": "Tajon Buchanan",
    "18": "Liam Millar",
    "19": "Cyle Larin",
    "20": "Jonathan David"
  },
  "CIV": {
    "1": "Emblem",
    "2": "Yahia Fofana",
    "3": "Ghislain Konan",
    "4": "Wilfried Singo",
    "5": "Odilon Kossounou",
    "6": "Evan Ndicka",
    "7": "Willy Boly",
    "8": "Emmanuel Agbadou",
    "9": "Ousmane Diomande",
    "10": "Franck Kessié",
    "11": "Seko Fofana",
    "12": "Ibrahim Sangaré",
    "13": "Team Photo",
    "14": "Jean-Philippe Gbamin",
    "15": "Amad Diallo",
    "16": "Sébastien Haller",
    "17": "Simon Adingra",
    "18": "Yan Diomandé",
    "19": "Evann Guessand",
    "20": "Oumar Diakité"
  },
  "COD": {
    "1": "Emblem",
    "2": "Lionel Mpasi",
    "3": "Aaron Wan-Bissaka",
    "4": "Axel Tuanzebe",
    "5": "Arthur Masuaku",
    "6": "Chancel Mbemba",
    "7": "Joris Kayembe",
    "8": "Charles Pickel",
    "9": "Ngal'ayel Mukau",
    "10": "Edo Kayembe",
    "11": "Samuel Moutoussamy",
    "12": "Noah Sadiki",
    "13": "Team Photo",
    "14": "Théo Bongonda",
    "15": "Meschak Elia",
    "16": "Yoane Wissa",
    "17": "Brian Cipenga",
    "18": "Fiston Mayele",
    "19": "Cédric Bakambu",
    "20": "Nathanaël Mbuku"
  },
  "COL": {
    "1": "Emblem",
    "2": "Camilo Vargas",
    "3": "David Ospina",
    "4": "Dávinson Sánchez",
    "5": "Yerry Mina",
    "6": "Daniel Muñoz",
    "7": "Johan Mojica",
    "8": "Jhon Lucumí",
    "9": "Santiago Arias",
    "10": "Jefferson Lerma",
    "11": "Kevin Castaño",
    "12": "Richard Ríos",
    "13": "Team Photo",
    "14": "James Rodríguez",
    "15": "Juan Fernando Quintero",
    "16": "Jorge Carrascal",
    "17": "Jhon Arias",
    "18": "Jhon Córdoba",
    "19": "Luis Suárez",
    "20": "Luis Díaz"
  },
  "CPV": {
    "1": "Emblem",
    "2": "Vozinha",
    "3": "Logan Costa",
    "4": "Pico",
    "5": "Diney",
    "6": "Steven Moreira",
    "7": "Wagner Pina",
    "8": "João Paulo",
    "9": "Yannick Semedo",
    "10": "Kevin Pina",
    "11": "Patrick Andrade",
    "12": "Jamiro Monteiro",
    "13": "Team Photo",
    "14": "Deroy Duarte",
    "15": "Garry Rodrigues",
    "16": "Jovane Cabral",
    "17": "Ryan Mendes",
    "18": "Dailon Livramento",
    "19": "Willy Semedo",
    "20": "Bebé"
  },
  "CRO": {
    "1": "Emblem",
    "2": "Dominik Livaković",
    "3": "Duško Ćaleta-Car",
    "4": "Joško Gvardiol",
    "5": "Josip Stanišić",
    "6": "Luka Vušković",
    "7": "Josip Šutalo",
    "8": "Kristijan Jakić",
    "9": "Luka Modrić",
    "10": "Mateo Kovačić",
    "11": "Martin Baturina",
    "12": "Lovro Majer",
    "13": "Team Photo",
    "14": "Mario Pašalić",
    "15": "Petar Sučić",
    "16": "Ivan Perišić",
    "17": "Marco Pašalić",
    "18": "Ante Budimir",
    "19": "Andrej Kramarić",
    "20": "Franjo Ivanović"
  },
  "CUW": {
    "1": "Emblem",
    "2": "Eloy Room",
    "3": "Armando Obispo",
    "4": "Sherel Floranus",
    "5": "Jurien Gaari",
    "6": "Joshua Brenet",
    "7": "Roshon van Eijma",
    "8": "Shurandy Sambo",
    "9": "Livano Comenencia",
    "10": "Godfried Roemeratoe",
    "11": "Juninho Bacuna",
    "12": "Leandro Bacuna",
    "13": "Team Photo",
    "14": "Tahith Chong",
    "15": "Kenji Gorré",
    "16": "Jearl Margaritha",
    "17": "Jürgen Locadia",
    "18": "Jeremy Antonisse",
    "19": "Gervane Kastaneer",
    "20": "Sontje Hansen"
  },
  "CZE": {
    "1": "Emblem",
    "2": "Matěj Kovář",
    "3": "Jindřich Staněk",
    "4": "Ladislav Krejčí",
    "5": "Vladimír Coufal",
    "6": "Jaroslav Zelený",
    "7": "Tomáš Holeš",
    "8": "David Zima",
    "9": "Michal Sadílek",
    "10": "Lukáš Provod",
    "11": "Lukáš Červ",
    "12": "Tomáš Souček",
    "13": "Team Photo",
    "14": "Pavel Šulc",
    "15": "Matěj Vydra",
    "16": "Vasil Kušej",
    "17": "Tomáš Chorý",
    "18": "Václav Černý",
    "19": "Adam Hložek",
    "20": "Patrik Schick"
  },
  "ECU": {
    "1": "Emblem",
    "2": "Hernán Galíndez",
    "3": "Gonzalo Valle",
    "4": "Piero Hincapié",
    "5": "Pervis Estupiñán",
    "6": "Willian Pacho",
    "7": "Ángelo Preciado",
    "8": "Joel Ordóñez",
    "9": "Moisés Caicedo",
    "10": "Alan Franco",
    "11": "Kendry Páez",
    "12": "Pedro Vite",
    "13": "Team Photo",
    "14": "John Yeboah",
    "15": "Leonardo Campana",
    "16": "Gonzalo Plata",
    "17": "Nilson Angulo",
    "18": "Alan Minda",
    "19": "Kevin Rodríguez",
    "20": "Enner Valencia"
  },
  "EGY": {
    "1": "Emblem",
    "2": "Mohamed El Shenawy",
    "3": "Mohamed Hany",
    "4": "Mohamed Hamdy",
    "5": "Yasser Ibrahim",
    "6": "Khaled Sobhi",
    "7": "Ramy Rabia",
    "8": "Hossam Abdelmaguid",
    "9": "Ahmed Fattouh",
    "10": "Marwan Attia",
    "11": "Zizo",
    "12": "Hamdy Fathy",
    "13": "Team Photo",
    "14": "Mohamed Magdy",
    "15": "Emam Ashour",
    "16": "Osama Faisal",
    "17": "Mohamed Salah",
    "18": "Mostafa Mohamed",
    "19": "Trézéguet",
    "20": "Omar Marmoush"
  },
  "ENG": {
    "1": "Emblem",
    "2": "Jordan Pickford",
    "3": "John Stones",
    "4": "Marc Guéhi",
    "5": "Ezri Konsa",
    "6": "Trent Alexander-Arnold",
    "7": "Reece James",
    "8": "Dan Burn",
    "9": "Jordan Henderson",
    "10": "Declan Rice",
    "11": "Jude Bellingham",
    "12": "Cole Palmer",
    "13": "Team Photo",
    "14": "Morgan Rogers",
    "15": "Anthony Gordon",
    "16": "Phil Foden",
    "17": "Bukayo Saka",
    "18": "Harry Kane",
    "19": "Marcus Rashford",
    "20": "Ollie Watkins"
  },
  "ESP": {
    "1": "Emblem",
    "2": "Unai Simón",
    "3": "Robin Le Normand",
    "4": "Aymeric Laporte",
    "5": "Dean Huijsen",
    "6": "Pedro Porro",
    "7": "Dani Carvajal",
    "8": "Marc Cucurella",
    "9": "Martín Zubimendi",
    "10": "Rodri",
    "11": "Pedri",
    "12": "Fabián Ruiz",
    "13": "Team Photo",
    "14": "Mikel Merino",
    "15": "Lamine Yamal",
    "16": "Dani Olmo",
    "17": "Nico Williams",
    "18": "Ferran Torres",
    "19": "Álvaro Morata",
    "20": "Mikel Oyarzabal"
  },
  "FRA": {
    "1": "Emblem",
    "2": "Mike Maignan",
    "3": "Theo Hernández",
    "4": "William Saliba",
    "5": "Jules Koundé",
    "6": "Ibrahima Konaté",
    "7": "Dayot Upamecano",
    "8": "Lucas Digne",
    "9": "Aurélien Tchouaméni",
    "10": "Eduardo Camavinga",
    "11": "Manu Koné",
    "12": "Adrien Rabiot",
    "13": "Team Photo",
    "14": "Michael Olise",
    "15": "Ousmane Dembélé",
    "16": "Bradley Barcola",
    "17": "Désiré Doué",
    "18": "Kingsley Coman",
    "19": "Hugo Ekitike",
    "20": "Kylian Mbappé"
  },
  "GER": {
    "1": "Emblem",
    "2": "Marc-André ter Stegen",
    "3": "Jonathan Tah",
    "4": "David Raum",
    "5": "Nico Schlotterbeck",
    "6": "Antonio Rüdiger",
    "7": "Waldemar Anton",
    "8": "Ridle Baku",
    "9": "Maximilian Mittelstädt",
    "10": "Joshua Kimmich",
    "11": "Florian Wirtz",
    "12": "Felix Nmecha",
    "13": "Team Photo",
    "14": "Leon Goretzka",
    "15": "Jamal Musiala",
    "16": "Serge Gnabry",
    "17": "Kai Havertz",
    "18": "Leroy Sané",
    "19": "Karim Adeyemi",
    "20": "Nick Woltemade"
  },
  "GHA": {
    "1": "Emblem",
    "2": "Lawrence Ati-Zigi",
    "3": "Tariq Lamptey",
    "4": "Mohammed Salisu",
    "5": "Alidu Seidu",
    "6": "Alexander Djiku",
    "7": "Gideon Mensah",
    "8": "Caleb Yirenkyi",
    "9": "Abdul Fatawu Issahaku",
    "10": "Thomas Partey",
    "11": "Salis Abdul Samed",
    "12": "Kamaldeen Sulemana",
    "13": "Team Photo",
    "14": "Mohammed Kudus",
    "15": "Iñaki Williams",
    "16": "Jordan Ayew",
    "17": "André Ayew",
    "18": "Joseph Paintsil",
    "19": "Osman Bukari",
    "20": "Antoine Semenyo"
  },
  "HAI": {
    "1": "Emblem",
    "2": "Johny Placide",
    "3": "Carlens Arcus",
    "4": "Martin Expérience",
    "5": "Jean-Kévin Duverne",
    "6": "Ricardo Adé",
    "7": "Duke Lacroix",
    "8": "Garven Metusala",
    "9": "Hannes Delcroix",
    "10": "Leverton Pierre",
    "11": "Danley Jean Jacques",
    "12": "Jean-Ricner Bellegarde",
    "13": "Team Photo",
    "14": "Christopher Attys",
    "15": "Derrick Etienne Jr.",
    "16": "Josué Casimir",
    "17": "Rubén Providence",
    "18": "Duckens Nazon",
    "19": "Louicius Deedson",
    "20": "Frantzdy Pierrot"
  },
  "IRN": {
    "1": "Emblem",
    "2": "Alireza Beiranvand",
    "3": "Morteza Pouraliganji",
    "4": "Ehsan Hajsafi",
    "5": "Milad Mohammadi",
    "6": "Shojae Khalilzadeh",
    "7": "Ramin Rezaeian",
    "8": "Hossein Kanaani",
    "9": "Sadegh Moharrami",
    "10": "Saleh Hardani",
    "11": "Saeed Ezatolahi",
    "12": "Saman Ghoddos",
    "13": "Team Photo",
    "14": "Omid Noorafkan",
    "15": "Roozbeh Cheshmi",
    "16": "Mohammad Mohebi",
    "17": "Sardar Azmoun",
    "18": "Mehdi Taremi",
    "19": "Alireza Jahanbakhsh",
    "20": "Ali Gholizadeh"
  },
  "IRQ": {
    "1": "Emblem",
    "2": "Jalal Hassan",
    "3": "Rebin Sulaka",
    "4": "Hussein Ali",
    "5": "Akam Hashim",
    "6": "Merchas Doski",
    "7": "Zaid Tahseen",
    "8": "Manaf Younis",
    "9": "Zidane Iqbal",
    "10": "Amir Al-Ammari",
    "11": "Ibrahim Bayesh",
    "12": "Ali Jasim",
    "13": "Team Photo",
    "14": "Youssef Amyn",
    "15": "Aimar Sher",
    "16": "Marko Farji",
    "17": "Osama Rashid",
    "18": "Ali Al-Hamadi",
    "19": "Aymen Hussein",
    "20": "Mohanad Ali"
  },
  "JOR": {
    "1": "Emblem",
    "2": "Yazeed Abulaila",
    "3": "Ihsan Haddad",
    "4": "Mohammad Abu Hashish",
    "5": "Yazan Al-Arab",
    "6": "Abdallah Nasib",
    "7": "Saleem Obaid",
    "8": "Mohammad Abualnadi",
    "9": "Ibrahim Saadeh",
    "10": "Nizar Al-Rashdan",
    "11": "Noor Al-Rawabdeh",
    "12": "Mohannad Abu Taha",
    "13": "Team Photo",
    "14": "Amer Jamous",
    "15": "Mousa Al-Taamari",
    "16": "Yazan Al-Naimat",
    "17": "Mahmoud Al-Mardi",
    "18": "Ali Olwan",
    "19": "Mohammad Abu Zrayq",
    "20": "Ibrahim Sabra"
  },
  "JPN": {
    "1": "Emblem",
    "2": "Zion Suzuki",
    "3": "Henry Heroki Mochizuki",
    "4": "Ayumu Seko",
    "5": "Junnosuke Suzuki",
    "6": "Shogo Taniguchi",
    "7": "Tsuyoshi Watanabe",
    "8": "Kaishu Sano",
    "9": "Yuki Soma",
    "10": "Ao Tanaka",
    "11": "Daichi Kamada",
    "12": "Takefusa Kubo",
    "13": "Team Photo",
    "14": "Ritsu Dōan",
    "15": "Keito Nakamura",
    "16": "Takumi Minamino",
    "17": "Shuto Machino",
    "18": "Junya Ito",
    "19": "Koki Ogawa",
    "20": "Ayase Ueda"
  },
  "KOR": {
    "1": "Emblem",
    "2": "Hyeon-woo Jo",
    "3": "Seung-gyu Kim",
    "4": "Min-jae Kim",
    "5": "Yoo-min Cho",
    "6": "Young-woo Seol",
    "7": "Han-beom Lee",
    "8": "Tae-seok Lee",
    "9": "Myung-jae Lee",
    "10": "Jae-sung Lee",
    "11": "In-beom Hwang",
    "12": "Kang-in Lee",
    "13": "Team Photo",
    "14": "Seung-ho Paik",
    "15": "Jens Castrop",
    "16": "Dong-kyung Lee",
    "17": "Gue-sung Cho",
    "18": "Heung-min Son",
    "19": "Hee-chan Hwang",
    "20": "Hyeon-gyu Oh"
  },
  "KSA": {
    "1": "Emblem",
    "2": "Nawaf Alaqidi",
    "3": "Abdulrahman Al-Sanbi",
    "4": "Saud Abdulhamid",
    "5": "Nawaf Boushal",
    "6": "Jihad Thakri",
    "7": "Moteb Al-Harbi",
    "8": "Hassan Al-Tambakti",
    "9": "Musab Al-Juwayr",
    "10": "Ziyad Al-Johani",
    "11": "Abdullah Al-Khaibari",
    "12": "Nasser Al-Dawsari",
    "13": "Team Photo",
    "14": "Saleh Abu Al-Shamat",
    "15": "Marwan Al-Sahafi",
    "16": "Salem Al-Dawsari",
    "17": "Abdulrahman Al-Aboud",
    "18": "Firas Al-Buraikan",
    "19": "Saleh Al-Shehri",
    "20": "Abdullah Al-Hamdan"
  },
  "MAR": {
    "1": "Emblem",
    "2": "Yassine Bounou",
    "3": "Munir El Kajoui",
    "4": "Achraf Hakimi",
    "5": "Noussair Mazraoui",
    "6": "Nayef Aguerd",
    "7": "Romain Saïss",
    "8": "Jawad El Yamiq",
    "9": "Adam Masina",
    "10": "Sofyan Amrabat",
    "11": "Azzedine Ounahi",
    "12": "Eliesse Ben Seghir",
    "13": "Team Photo",
    "14": "Bilal El Khannouss",
    "15": "Ismael Saibari",
    "16": "Youssef En-Nesyri",
    "17": "Abde Ezzalzouli",
    "18": "Soufiane Rahimi",
    "19": "Brahim Díaz",
    "20": "Ayoub El Kaabi"
  },
  "MEX": {
    "1": "Emblem",
    "2": "Luis Malagón",
    "3": "Johan Vásquez",
    "4": "Jorge Sánchez",
    "5": "César Montes",
    "6": "Jesús Gallardo",
    "7": "Israel Reyes",
    "8": "Diego Laínez",
    "9": "Carlos Rodríguez",
    "10": "Edson Álvarez",
    "11": "Orbelín Pineda",
    "12": "Marcel Ruiz",
    "13": "Team Photo",
    "14": "Érick Sánchez",
    "15": "Hirving Lozano",
    "16": "Santiago Giménez",
    "17": "Raúl Jiménez",
    "18": "Alexis Vega",
    "19": "Roberto Alvarado",
    "20": "César Huerta"
  },
  "NED": {
    "1": "Emblem",
    "2": "Bart Verbruggen",
    "3": "Virgil van Dijk",
    "4": "Micky van de Ven",
    "5": "Jurrien Timber",
    "6": "Denzel Dumfries",
    "7": "Nathan Aké",
    "8": "Jeremie Frimpong",
    "9": "Jan Paul van Hecke",
    "10": "Tijjani Reijnders",
    "11": "Ryan Gravenberch",
    "12": "Teun Koopmeiners",
    "13": "Team Photo",
    "14": "Frenkie de Jong",
    "15": "Xavi Simons",
    "16": "Justin Kluivert",
    "17": "Memphis Depay",
    "18": "Donyell Malen",
    "19": "Wout Weghorst",
    "20": "Cody Gakpo"
  },
  "NOR": {
    "1": "Emblem",
    "2": "Ørjan Nyland",
    "3": "Julian Ryerson",
    "4": "Leo Østigård",
    "5": "Kristoffer Vassbakk Ajer",
    "6": "Marcus Holmgren Pedersen",
    "7": "David Møller Wolfe",
    "8": "Torbjørn Heggem",
    "9": "Morten Thorsby",
    "10": "Martin Ødegaard",
    "11": "Sander Berge",
    "12": "Andreas Schjelderup",
    "13": "Team Photo",
    "14": "Patrick Berg",
    "15": "Erling Haaland",
    "16": "Alexander Sørloth",
    "17": "Aron Dønnum",
    "18": "Jørgen Strand Larsen",
    "19": "Antonio Nusa",
    "20": "Oscar Bobb"
  },
  "NZL": {
    "1": "Emblem",
    "2": "Max Crocombe",
    "3": "Alex Paulsen",
    "4": "Michael Boxall",
    "5": "Liberato Cacace",
    "6": "Tim Payne",
    "7": "Tyler Bindon",
    "8": "Francis de Vries",
    "9": "Finn Surman",
    "10": "Joe Bell",
    "11": "Sarpreet Singh",
    "12": "Ryan Thomas",
    "13": "Team Photo",
    "14": "Matthew Garbett",
    "15": "Marko Stamenić",
    "16": "Ben Old",
    "17": "Chris Wood",
    "18": "Elijah Just",
    "19": "Callum McCowatt",
    "20": "Kosta Barbarouses"
  },
  "PAN": {
    "1": "Emblem",
    "2": "Orlando Mosquera",
    "3": "Luis Mejía",
    "4": "Fidel Escobar",
    "5": "Andrés Andrade",
    "6": "Michael Amir Murillo",
    "7": "Eric Davis",
    "8": "José Córdoba",
    "9": "César Blackman",
    "10": "Cristian Martínez",
    "11": "Aníbal Godoy",
    "12": "Adalberto Carrasquilla",
    "13": "Team Photo",
    "14": "Édgar Bárcenas",
    "15": "Carlos Harvey",
    "16": "Ismael Díaz",
    "17": "José Fajardo",
    "18": "Cecilio Waterman",
    "19": "José Luis Rodríguez",
    "20": "Alberto Quintero"
  },
  "PAR": {
    "1": "Emblem",
    "2": "Roberto Fernández",
    "3": "Orlando Gill",
    "4": "Gustavo Gómez",
    "5": "Fabián Balbuena",
    "6": "Juan José Cáceres",
    "7": "Omar Alderete",
    "8": "Junior Alonso",
    "9": "Mathías Villasanti",
    "10": "Diego Gómez",
    "11": "Damián Bobadilla",
    "12": "Andrés Cubas",
    "13": "Team Photo",
    "14": "Matías Galarza Fonda",
    "15": "Julio Enciso",
    "16": "Alejandro Romero Gamarra",
    "17": "Miguel Almirón",
    "18": "Ramón Sosa",
    "19": "Ángel Romero",
    "20": "Antonio Sanabria"
  },
  "POR": {
    "1": "Emblem",
    "2": "Diogo Costa",
    "3": "José Sá",
    "4": "Rúben Dias",
    "5": "João Cancelo",
    "6": "Diogo Dalot",
    "7": "Nuno Mendes",
    "8": "Gonçalo Inácio",
    "9": "Bernardo Silva",
    "10": "Bruno Fernandes",
    "11": "Rúben Neves",
    "12": "Vitinha",
    "13": "Team Photo",
    "14": "João Neves",
    "15": "Cristiano Ronaldo",
    "16": "Francisco Trincão",
    "17": "João Félix",
    "18": "Gonçalo Ramos",
    "19": "Pedro Neto",
    "20": "Rafael Leão"
  },
  "QAT": {
    "1": "Emblem",
    "2": "Meshaal Barsham",
    "3": "Sultan Al Brake",
    "4": "Lucas Mendes",
    "5": "Homam Ahmed",
    "6": "Boualem Khoukhi",
    "7": "Pedro Miguel",
    "8": "Tarek Salman",
    "9": "Mohamed Al-Mannai",
    "10": "Karim Boudiaf",
    "11": "Assim Madibo",
    "12": "Ahmed Fatehi",
    "13": "Team Photo",
    "14": "Mohammed Waad",
    "15": "Abdulaziz Hatem",
    "16": "Hassan Al-Haydos",
    "17": "Edmilson Junior",
    "18": "Akram Afif",
    "19": "Ahmed Al Ganehi",
    "20": "Almoez Ali"
  },
  "RSA": {
    "1": "Emblem",
    "2": "Ronwen Williams",
    "3": "Sipho Chaine",
    "4": "Aubrey Modiba",
    "5": "Samukele Kabini",
    "6": "Mbekezeli Mbokazi",
    "7": "Khulumani Ndamane",
    "8": "Siyabonga Ngezana",
    "9": "Khuliso Mudau",
    "10": "Nkosinathi Sibisi",
    "11": "Teboho Mokoena",
    "12": "Thalente Mbatha",
    "13": "Team Photo",
    "14": "Bathusi Aubaas",
    "15": "Yaya Sithole",
    "16": "Sipho Mbule",
    "17": "Lyle Foster",
    "18": "Iqraam Rayners",
    "19": "Mohau Nkota",
    "20": "Oswin Appollis"
  },
  "SCO": {
    "1": "Emblem",
    "2": "Angus Gunn",
    "3": "Jack Hendry",
    "4": "Kieran Tierney",
    "5": "Aaron Hickey",
    "6": "Andrew Robertson",
    "7": "Scott McKenna",
    "8": "John Souttar",
    "9": "Anthony Ralston",
    "10": "Grant Hanley",
    "11": "Scott McTominay",
    "12": "Billy Gilmour",
    "13": "Team Photo",
    "14": "Lewis Ferguson",
    "15": "Ryan Christie",
    "16": "Kenny McLean",
    "17": "John McGinn",
    "18": "Lyndon Dykes",
    "19": "Che Adams",
    "20": "Ben Doak"
  },
  "SEN": {
    "1": "Emblem",
    "2": "Édouard Mendy",
    "3": "Yehvann Diouf",
    "4": "Moussa Niakhaté",
    "5": "Abdoulaye Seck",
    "6": "Ismaïl Jakobs",
    "7": "El Hadji Malick Diouf",
    "8": "Kalidou Koulibaly",
    "9": "Idrissa Gana Gueye",
    "10": "Pape Matar Sarr",
    "11": "Pape Gueye",
    "12": "Habib Diarra",
    "13": "Team Photo",
    "14": "Lamine Camara",
    "15": "Sadio Mané",
    "16": "Ismaïla Sarr",
    "17": "Boulaye Dia",
    "18": "Iliman Ndiaye",
    "19": "Nicolas Jackson",
    "20": "Krépin Diatta"
  },
  "SUI": {
    "1": "Emblem",
    "2": "Gregor Kobel",
    "3": "Yvon Mvogo",
    "4": "Manuel Akanji",
    "5": "Ricardo Rodríguez",
    "6": "Nico Elvedi",
    "7": "Aurèle Amenda",
    "8": "Silvan Widmer",
    "9": "Granit Xhaka",
    "10": "Denis Zakaria",
    "11": "Remo Freuler",
    "12": "Fabian Rieder",
    "13": "Team Photo",
    "14": "Ardon Jashari",
    "15": "Johan Manzambi",
    "16": "Michel Aebischer",
    "17": "Breel Embolo",
    "18": "Rubén Vargas",
    "19": "Dan Ndoye",
    "20": "Zeki Amdouni"
  },
  "SWE": {
    "1": "Emblem",
    "2": "Victor Johansson",
    "3": "Isak Hien",
    "4": "Gabriel Gudmundsson",
    "5": "Emil Holm",
    "6": "Victor Nilsson Lindelöf",
    "7": "Gustaf Lagerbielke",
    "8": "Lucas Bergvall",
    "9": "Hugo Larsson",
    "10": "Jesper Karlström",
    "11": "Yasin Ayari",
    "12": "Mattias Svanberg",
    "13": "Team Photo",
    "14": "Daniel Svensson",
    "15": "Ken Sema",
    "16": "Roony Bardghji",
    "17": "Dejan Kulusevski",
    "18": "Anthony Elanga",
    "19": "Alexander Isak",
    "20": "Viktor Gyökeres"
  },
  "TUN": {
    "1": "Emblem",
    "2": "Béchir Ben Saïd",
    "3": "Aymen Dahmen",
    "4": "Van Valery",
    "5": "Montassar Talbi",
    "6": "Yassine Meriah",
    "7": "Ali Abdi",
    "8": "Dylan Bronn",
    "9": "Ellyes Skhiri",
    "10": "Aïssa Laïdouni",
    "11": "Ferjani Sassi",
    "12": "Mohamed Ali Ben Romdhane",
    "13": "Team Photo",
    "14": "Hannibal Mejbri",
    "15": "Elias Achouri",
    "16": "Elias Saad",
    "17": "Hazem Mastouri",
    "18": "Ismaël Gharbi",
    "19": "Sayfallah Ltaief",
    "20": "Naïm Sliti"
  },
  "TUR": {
    "1": "Emblem",
    "2": "Uğurcan Çakır",
    "3": "Mert Müldür",
    "4": "Zeki Çelik",
    "5": "Abdülkerim Bardakcı",
    "6": "Çağlar Söyüncü",
    "7": "Merih Demiral",
    "8": "Ferdi Kadıoğlu",
    "9": "Kaan Ayhan",
    "10": "İsmail Yüksek",
    "11": "Hakan Çalhanoğlu",
    "12": "Orkun Kökçü",
    "13": "Team Photo",
    "14": "Arda Güler",
    "15": "İrfan Can Kahveci",
    "16": "Yunus Akgün",
    "17": "Can Uzun",
    "18": "Barış Alper Yılmaz",
    "19": "Kerem Aktürkoğlu",
    "20": "Kenan Yıldız"
  },
  "URU": {
    "1": "Emblem",
    "2": "Sergio Rochet",
    "3": "Santiago Mele",
    "4": "Ronald Araújo",
    "5": "José María Giménez",
    "6": "Sebastián Cáceres",
    "7": "Mathías Olivera",
    "8": "Guillermo Varela",
    "9": "Nahitan Nández",
    "10": "Federico Valverde",
    "11": "Giorgian De Arrascaeta",
    "12": "Rodrigo Bentancur",
    "13": "Team Photo",
    "14": "Manuel Ugarte",
    "15": "Nicolás de la Cruz",
    "16": "Maxi Araújo",
    "17": "Darwin Núñez",
    "18": "Federico Viñas",
    "19": "Rodrigo Aguirre",
    "20": "Facundo Pellistri"
  },
  "USA": {
    "1": "Emblem",
    "2": "Matt Freese",
    "3": "Chris Richards",
    "4": "Tim Ream",
    "5": "Mark McKenzie",
    "6": "Alex Freeman",
    "7": "Antonee Robinson",
    "8": "Tyler Adams",
    "9": "Tanner Tessmann",
    "10": "Weston McKennie",
    "11": "Christian Roldan",
    "12": "Timothy Weah",
    "13": "Team Photo",
    "14": "Diego Luna",
    "15": "Malik Tillman",
    "16": "Christian Pulisic",
    "17": "Brenden Aaronson",
    "18": "Ricardo Pepi",
    "19": "Haji Wright",
    "20": "Folarin Balogun"
  },
  "UZB": {
    "1": "Emblem",
    "2": "Otkir Yusupov",
    "3": "Farrukh Sayfiev",
    "4": "Sherzod Nasrullaev",
    "5": "Otabek Shukurov",
    "6": "Husniddin Aliqulov",
    "7": "Rustamjon Ashurmatov",
    "8": "Khojiakbar Alijonov",
    "9": "Abdukodir Khusanov",
    "10": "Odiljon Hamrobekov",
    "11": "Otabek Shukurov",
    "12": "Jamshid Iskanderov",
    "13": "Team Photo",
    "14": "Azizbek Turgunboev",
    "15": "Khojimat Erkinov",
    "16": "Eldor Shomurodov",
    "17": "Oston Urunov",
    "18": "Jaloliddin Masharipov",
    "19": "Igor Sergeev",
    "20": "Abbosbek Fayzullaev"
  }
};

const ALBUM_TEAM_CODES: string[] = [
  "ALG",
  "ARG",
  "AUS",
  "AUT",
  "BEL",
  "BIH",
  "BRA",
  "CAN",
  "CIV",
  "COD",
  "COL",
  "CPV",
  "CRO",
  "CUW",
  "CZE",
  "ECU",
  "EGY",
  "ENG",
  "ESP",
  "FRA",
  "GER",
  "GHA",
  "HAI",
  "IRN",
  "IRQ",
  "JOR",
  "JPN",
  "KOR",
  "KSA",
  "MAR",
  "MEX",
  "NED",
  "NOR",
  "NZL",
  "PAN",
  "PAR",
  "POR",
  "QAT",
  "RSA",
  "SCO",
  "SEN",
  "SUI",
  "SWE",
  "TUN",
  "TUR",
  "URU",
  "USA",
  "UZB"
];

const FWC_STICKER_NAMES: { [id: number]: string } = {
  "1": "Official Emblem - Part 1",
  "2": "Official Emblem - Part 2",
  "3": "Official Mascots",
  "4": "Official Slogan",
  "5": "Official Ball",
  "6": "Canada (Host Country Emblem)",
  "7": "Mexico (Host Country Emblem)",
  "8": "USA (Host Country Emblem)",
  "9": "Team Photo (Italy 1934) - FIFA World Cup Italy 1934",
  "10": "Team Photo (Uruguay 1950) - FIFA World Cup Brazil 1950",
  "11": "Team Photo (West Germany 1954) - FIFA World Cup Switzerland 1954",
  "12": "Team Photo (Brazil 1962) - FIFA World Cup Chile 1962",
  "13": "Team Photo (West Germany 1974) - FIFA World Cup 1974",
  "14": "Team Photo (Argentina 1986) - FIFA World Cup Mexico 1986",
  "15": "Team Photo (Brazil 1994) - FIFA World Cup USA 1994",
  "16": "Team Photo (Brazil 2002) - FIFA World Cup Korea/Japan 2002",
  "17": "Team Photo (Italy 2006) - FIFA World Cup Germany 2006",
  "18": "Team Photo (Germany 2014) - FIFA World Cup Brazil 2014",
  "19": "Team Photo (Argentina 2022) - FIFA World Cup Qatar 2022"
};

function getStickerPosition(num: number): 'Emblem' | 'GK' | 'DF' | 'MF' | 'FW' | 'Team Photo' {
  if (num === 1) return 'Emblem';
  if (num === 13) return 'Team Photo';
  if (num === 2) return 'GK';
  if ([3, 4, 5, 14, 15].includes(num)) return 'DF';
  if ([6, 7, 8, 9, 16, 17].includes(num)) return 'MF';
  return 'FW';
}

export function getPlayerName(teamCode: string, num: number): string {
  return PLAYER_NAMES_BY_TEAM[teamCode]?.[num] ?? (
    num === 1 ? "Emblem" :
    num === 13 ? "Team Photo" :
    `Unknown Player ${teamCode}-${num}`
  );
}

// Generates the static 980 sticker collection definition array
export function generateAllStickers(): Sticker[] {
  const stickers: Sticker[] = [];

  // 1. Sticker 00: Panini Logo
  stickers.push({
    id: "00",
    name: "Panini Logo",
    type: 'general',
    section: "Tournament Information",
    number: 0,
    isShiny: true,
    position: 'Special'
  });

  // 2. FWC-1 to FWC-8: Tournament information + host countries and cities
  for (let i = 1; i <= 8; i++) {
    stickers.push({
      id: `FWC-${i}`,
      name: FWC_STICKER_NAMES[i],
      type: 'general',
      section: i <= 5 ? "Tournament Information" : "Host Countries and Cities",
      number: i,
      isShiny: true,
      position: 'Special'
    });
  }

  // 3. Team sections: 48 teams × 20 stickers = 960 stickers
  for (const teamCode of ALBUM_TEAM_CODES) {
    const team = TEAMS.find((t) => t.code === teamCode);
    if (!team) continue;

    for (let i = 1; i <= 20; i++) {
      stickers.push({
        id: `${team.code}-${i}`,
        name: getPlayerName(team.code, i),
        type: 'team',
        section: `${team.name} (${team.code})`,
        teamCode: team.code,
        number: i,
        isShiny: i === 1, // Only the emblem of the federation is metallic foil!
        position: getStickerPosition(i)
      });
    }
  }

  // 4. FIFA World Cup History: FWC-9 to FWC-19
  for (let i = 9; i <= 19; i++) {
    stickers.push({
      id: `FWC-${i}`,
      name: FWC_STICKER_NAMES[i],
      type: 'history',
      section: "FIFA World Cup History",
      number: i,
      isShiny: true, // Shiny golden historic badges
      position: 'Special'
    });
  }

  return stickers;
}

// Generate an initial empty collection state.
export function generateInitialCollectionState(): CollectionState {
  const allStickers = generateAllStickers();
  const counts: { [stickerId: string]: number } = {};

  // Initialize everything to 0
  for (const s of allStickers) {
    counts[s.id] = 0;
  }

  return {
    counts,
    photos: {}
  };
}

// Beautiful list of community trader profiles and listings to simulate active community matches
export const COMMUNITY_TRADERS: TradeOffer[] = [
  {
    id: "trade-1",
    traderName: "John (The Swap Master)",
    gives: ["FWC-7"], // Mexico host country emblem
    wants: ["MEX-16", "ARG-17"], // Santiago Giménez, Lionel Messi
    status: 'pending'
  },
  {
    id: "trade-2",
    traderName: "Alex88",
    gives: ["MEX-10"], // Edson Álvarez
    wants: ["CAN-1"], // Canada emblem
    status: 'pending'
  },
  {
    id: "trade-3",
    traderName: "KylianFan",
    gives: ["FRA-20"], // Kylian Mbappé
    wants: ["ENG-18"], // Harry Kane
    status: 'pending'
  },
  {
    id: "trade-4",
    traderName: "ZizouLegend",
    gives: ["FWC-19"],
    wants: ["POR-15"], // Cristiano Ronaldo
    status: 'pending'
  }
];
